apiVersion: v2
name: workflow-platform
description: A Helm chart for WorkflowPlatform - Workflow Orchestration Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - workflow
  - orchestration
  - platform
  - automation
home: https://github.com/ribatshepo/WorkFlowOchestrator
sources:
  - https://github.com/ribatshepo/WorkFlowOchestrator
maintainers:
  - name: WorkflowPlatform Team
    email: team@workflowplatform.com
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: rabbitmq
    version: "11.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
annotations:
  category: Developer Tools
  licenses: MIT
