apiVersion: v2
name: workflow-platform
description: A Helm chart for WorkflowPlatform - Enterprise Workflow Orchestration Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - workflow
  - orchestration
  - platform
  - automation
  - enterprise
home: https://github.com/ribatshepo/WorkFlowOchestrator
sources:
  - https://github.com/ribatshepo/WorkFlowOchestrator
maintainers:
  - name: WorkflowPlatform Team
    email: team@workflowplatform.com

annotations:
  # Security and deployment notes
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - Fixed hardcoded credentials in Helm templates
    - Added support for external secrets
    - Enhanced security configuration options
    - Added production-ready value templates
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: rabbitmq
    version: "11.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
