# Kubernetes Secret Examples for Production Deployment
# DO NOT COMMIT ACTUAL SECRETS TO SOURCE CONTROL

apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: workflow-platform
type: Opaque
stringData:
  connection-string: "Host=your-db-host;Port=5432;Database=WorkflowPlatform;Username=your-username;Password=your-secure-password"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: workflow-platform
type: Opaque
stringData:
  connection-string: "your-redis-host:6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: workflow-platform
type: Opaque
stringData:
  connection-string: "amqp://your-username:your-secure-password@your-rabbitmq-host:5672/"

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: workflow-platform
type: Opaque
stringData:
  jwt-secret-key: "your-256-bit-jwt-secret-key-here-must-be-very-secure-and-random"
  jwt-issuer-key: "workflow-platform-production"
  jwt-audience-key: "workflow-platform-users"

---
# Example using external secret operator (recommended for production)
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: vault-backend
#   namespace: workflow-platform
# spec:
#   vault:
#     server: "https://vault.yourdomain.com"
#     path: "secret"
#     version: "v2"
#     auth:
#       kubernetes:
#         mountPath: "kubernetes"
#         role: "workflow-platform"
#         serviceAccountRef:
#           name: "workflow-platform"

---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: database-secret
#   namespace: workflow-platform
# spec:
#   refreshInterval: 15s
#   secretStoreRef:
#     name: vault-backend
#     kind: SecretStore
#   target:
#     name: database-secret
#     creationPolicy: Owner
#   data:
#   - secretKey: connection-string
#     remoteRef:
#       key: workflow-platform/database
#       property: connection-string
