# Default values for workflow-platform
# This is a YAML-formatted file.

global:
  imageRegistry: ghcr.io
  imagePullSecrets: []
  storageClass: ""
  environment: development

replicaCount: 1

api:
  image:
    repository: ghcr.io/ribatshepo/workfloworchestrator/api
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}

  podAnnotations: {}
  podSecurityContext:
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
        - ALL

frontend:
  image:
    repository: ghcr.io/ribatshepo/workfloworchestrator/frontend
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

  podAnnotations: {}
  podSecurityContext:
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
        - ALL

serviceAccount:
  create: true
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: workflow-platform.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend
            port: 80
        - path: /api
          pathType: Prefix
          service:
            name: api
            port: 8080
  tls: []

database:
  external: false
  host: postgresql
  port: 5432
  name: WorkflowPlatform
  username: "" # Should be set via existing secret or values override
  password: "" # Should be set via existing secret or values override
  existingSecret: ""
  secretKey: connection-string

redis:
  external: false
  host: redis-master
  port: 6379
  existingSecret: ""
  secretKey: connection-string

rabbitmq:
  external: false
  host: rabbitmq
  port: 5672
  username: "" # Should be set via existing secret or values override
  password: "" # Should be set via existing secret or values override
  existingSecret: ""
  secretKey: connection-string

jwt:
  existingSecret: ""
  secretKeys:
    secret: secret
    issuer: issuer
    audience: audience

# PostgreSQL subchart configuration
postgresql:
  enabled: true
  auth:
    # SECURITY NOTE: These values should be overridden in production
    # Use external secrets or helm install --set flags
    postgresPassword: "" # Override with --set postgresql.auth.postgresPassword=<value>
    username: "" # Override with --set postgresql.auth.username=<value>
    password: "" # Override with --set postgresql.auth.password=<value>
    database: "WorkflowPlatform"
  primary:
    persistence:
      enabled: true
      size: 8Gi
  metrics:
    enabled: true

# External services configuration
externalServices:
  # Redis subchart configuration
  redis:
    enabled: true
    auth:
      enabled: true
      password: "" # Override with --set externalServices.redis.auth.password=<value>
    master:
      persistence:
        enabled: true
        size: 8Gi
    metrics:
      enabled: true

  # RabbitMQ subchart configuration
  rabbitmq:
    enabled: true
    auth:
      username: "" # Override with --set externalServices.rabbitmq.auth.username=<value>
      password: "" # Override with --set externalServices.rabbitmq.auth.password=<value>
    persistence:
      enabled: true
      size: 8Gi
    metrics:
      enabled: true

monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
  grafana:
    enabled: false

security:
  podSecurityPolicy:
    enabled: false
  networkPolicy:
    enabled: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

# Additional labels to apply to all resources
commonLabels: {}

# Additional annotations to apply to all resources
commonAnnotations: {}
