# Production environment values for WorkflowPlatform
# This file contains production-specific configurations

global:
  environment: production

# Production resource allocation (higher than staging)
api:
  replicaCount: 3

  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 70

frontend:
  replicaCount: 3

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# External dependencies for production
postgresql:
  enabled: false # Use external managed database in production

externalServices:
  redis:
    enabled: false # Use external managed Redis in production

  rabbitmq:
    enabled: false # Use external managed RabbitMQ in production

# External service configuration
database:
  external: true
  host: "production-postgres.example.com"
  port: 5432
  name: "WorkflowPlatform"
  existingSecret: "workflow-platform-secrets"
  secretKey: "database-connection-string"

redis:
  external: true
  host: "production-redis.example.com"
  port: 6379
  existingSecret: "workflow-platform-secrets"
  secretKey: "redis-connection-string"

rabbitmq:
  external: true
  host: "production-rabbitmq.example.com"
  port: 5672
  existingSecret: "workflow-platform-secrets"
  secretKey: "rabbitmq-connection-string"

# Production ingress with TLS
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: workflow-platform.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend
            port: 80
        - path: /api
          pathType: Prefix
          service:
            name: api
            port: 8080
  tls:
    - secretName: workflow-platform-tls
      hosts:
        - workflow-platform.example.com

# Full monitoring suite for production
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
  grafana:
    enabled: true

# Production security settings
security:
  podSecurityPolicy:
    enabled: true
  networkPolicy:
    enabled: true

# Node affinity for production workloads
nodeScheduling:
  api:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-type
                  operator: In
                  values:
                    - production
    nodeSelector:
      environment: production

  frontend:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-type
                  operator: In
                  values:
                    - production
    nodeSelector:
      environment: production
