# Staging environment values for WorkflowPlatform
# This file contains staging-specific configurations

global:
  environment: staging

# Staging resource limits (smaller than production)
api:
  replicaCount: 2

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

frontend:
  replicaCount: 2

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# External dependencies for staging
postgresql:
  enabled: true
  auth:
    database: "WorkflowPlatformStaging"
  primary:
    persistence:
      size: 4Gi

externalServices:
  redis:
    enabled: true
    master:
      persistence:
        size: 2Gi

  rabbitmq:
    enabled: true
    persistence:
      size: 2Gi

# Ingress configuration for staging
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - host: workflow-platform-staging.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend
            port: 80
        - path: /api
          pathType: Prefix
          service:
            name: api
            port: 8080

# Monitoring enabled for staging
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
