# Prometheus configuration for WorkflowPlatform Development Environment
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # WorkflowPlatform API
  - job_name: "workflow-api"
    static_configs:
      - targets: ["workflow-api:8080"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s

  # Redis metrics (requires redis_exporter)
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s

  # RabbitMQ metrics (built-in Prometheus support)
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s

# Alerting configuration (for future implementation)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
